---
# tasks file for install_docker2ubuntu
- name: Update repositories cache
  apt:
    update_cache: yes
  become: true

- name: Install python
  apt:
    name: python3-pip
  become: true

# install packages
- name: Install docker
  shell: curl https://get.docker.com | sh

- name: Modify privilege
  become: true
  shell: usermod -aG docker ubuntu

- name: Change privilege of docker
  become: true
  file: dest=/usr/bin/docker mode=+x

- name: python docker / docker-compse module
  pip:
    name:
        - docker
        - docker-compose

# restart docker service
- name: Install docker
  shell: systemctl restart docker
  become: true