---
- name: Final_Project_Jenkins
  hosts: jenkins_server

  roles:
    - role: install_docker2centos

- name: Final_Project_Prod_Server
  hosts: project_servers

  roles:
    - role: install_docker2ubuntu
